/*
 * This source file was generated by the Gradle 'init' task
 */
package learn_kotlin;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Calling Kotlin functions
        System.out.println(HelloKt.getGreeting());
        HelloKt.printSum(10, 20);
        int result = HelloKt.sum(5, 7);
        System.out.println("Result of sum(5, 7) is: " + result);

        System.out.println("\n--- Kotlin Tour: Hello World ---");
        KotlinTourKt.showHelloWorld();
        KotlinTourKt.demonstrateVariables();
        KotlinTourKt.demonstrateStringTemplates();
        KotlinTourKt.introducePerson("Mary", 20);

        System.out.println("\n--- Kotlin Tour: Basic Types ---");
        BasicTypesKt.demonstrateTypeInference();
        BasicTypesKt.demonstrateExplicitTypes();
        BasicTypesKt.demonstrateDeferredInitialization();
        BasicTypesKt.runBasicTypesExercise();

        System.out.println("\n--- Kotlin Tour: Collections ---");
        CollectionsKt.demonstrateLists();
        CollectionsKt.demonstrateSets();
        CollectionsKt.demonstrateMaps();
        CollectionsKt.runCollectionsExercises();

        System.out.println("\n--- Kotlin Tour: Control Flow ---");
        ControlFlowKt.demonstrateIf();
        ControlFlowKt.demonstrateWhen();
        ControlFlowKt.demonstrateRanges();
        ControlFlowKt.demonstrateLoops();
        ControlFlowKt.runControlFlowExercises();

        System.out.println("\n--- Kotlin Tour: Functions ---");
        System.out.println("Sum: " + FunctionsKt.sumNumbers(10, 20));
        FunctionsKt.printMessageWithPrefix("Hello from Java!");
        FunctionsKt.printMessageWithPrefix("Custom Log", "Log");
        System.out.println("Single Sum: " + FunctionsKt.sumSingle(5, 5));
        System.out.println("Circle Area (r=2): " + FunctionsKt.circleArea(2));
        FunctionsKt.demonstrateLambdas();
        FunctionsKt.runFunctionsExercises();

        System.out.println("\n--- Kotlin Tour: Classes ---");
        ClassesKt.demonstrateClasses();

        // Direct class usage from Java
        Contact javaContact = new Contact(100, "java@interop.com");
        System.out.println("Java side - Contact email: " + javaContact.getEmail());
        javaContact.setEmail("updated_by_java@interop.com");
        javaContact.printInfo();

        System.out.println("\n--- Kotlin Tour: Null Safety ---");
        NullSafetyKt.demonstrateNullableTypes();
        System.out.println(NullSafetyKt.describeString("Hello"));
        System.out.println(NullSafetyKt.describeString(null));
        NullSafetyKt.demonstrateSafeCalls("safe");
        NullSafetyKt.demonstrateSafeCalls(null);
        NullSafetyKt.demonstrateElvisOperator("elvis");
        NullSafetyKt.demonstrateElvisOperator(null);
        NullSafetyKt.runNullSafetyExercise();

        System.out.println("\n--- Kotlin Tour: Extension Functions ---");
        ExtensionFunctionsKt.demonstrateExtensions();
        
        // Calling extension functions directly from Java as static methods
        String raw = "Java String";
        String bolded = ExtensionFunctionsKt.bold(raw);
        System.out.println("Bolded from Java: " + bolded);
        
        boolean positive = ExtensionFunctionsKt.isPositive(10);
        System.out.println("Is 10 positive (from Java)? " + positive);

        System.out.println("\n--- Kotlin Tour: Scope Functions ---");
        ScopeFunctionsKt.runScopeFunctions();

        System.out.println("\n--- Kotlin Tour: Lambdas with Receivers ---");
        LambdasWithReceiversKt.demonstrateLambdasWithReceivers();

        System.out.println("\n--- Kotlin Tour: Intermediate Classes & Interfaces ---");
        IntermediateClassesKt.demonstrateIntermediateClasses();

        System.out.println("\n--- Kotlin Tour: Objects ---");
        ObjectsKt.demonstrateObjects();

        System.out.println("\n--- Kotlin Tour: Special Classes ---");
        SpecialClassesKt.demonstrateSpecialClasses();

        System.out.println("\n--- Kotlin Tour: Properties ---");
        PropertiesKt.demonstrateProperties();

        System.out.println("\n--- Kotlin Tour: Intermediate Null Safety ---");
        IntermediateNullSafetyKt.demonstrateIntermediateNullSafety();

        System.out.println("\n--- Kotlin Tour: Libraries & APIs ---");
        LibrariesAndAPIsKt.demonstrateLibrariesAndAPIs();

        System.out.println("\n--- Kotlin: Basic Syntax Summary ---");
        BasicSyntaxKt.demonstrateBasicSyntax();

        System.out.println("\n--- Kotlin: Packages and Imports ---");
        PackagesKt.demonstratePackages();

        System.out.println("\n--- Kotlin: Annotations ---");
        AnnotationsKt.demonstrateAnnotations();

        System.out.println("\n--- Kotlin: Visibility Modifiers ---");
        VisibilityModifiersKt.demonstrateVisibility();

        System.out.println("\n--- Kotlin: Backing Properties Convention ---");
        BackingPropertiesKt.demonstrateBackingProperties();

        System.out.println("\n--- Kotlin Idiom: Execute if Null ---");
        IdiomsKt.demonstrateExecuteIfNull();

        System.out.println("\n--- Kotlin: Types Overview ---");
        TypesOverviewKt.demonstrateTypesOverview();

        System.out.println("\n--- Kotlin: Numbers ---");
        NumbersKt.demonstrateNumbers();

        System.out.println("\n--- Kotlin: Unsigned Integer Types ---");
        UnsignedNumbersKt.demonstrateUnsignedNumbers();

        System.out.println("\n--- Kotlin: Type Casts ---");
        TypeCastsKt.demonstrateTypeCasts();

        System.out.println("\n--- Kotlin: Type Aliases ---");
        TypeAliasesKt.demonstrateTypeAliases();

        System.out.println("\n--- Kotlin: Advanced Control Flow ---");
        ControlFlowAdvancedKt.demonstrateControlFlowAdvanced();

        System.out.println("\n--- Kotlin: Returns and Jumps ---");
        ReturnsAndJumpsKt.demonstrateReturnsAndJumps();

        System.out.println("\n--- Kotlin: Exceptions ---");
        ExceptionsAdvancedKt.demonstrateExceptionsAdvanced();

        System.out.println("\n--- Kotlin: Advanced Functions ---");
        FunctionsAdvancedKt.demonstrateFunctionsAdvanced();

        System.out.println("\n--- Kotlin: Lambdas & High-Order Functions ---");
        LambdasAdvancedKt.demonstrateLambdasAdvanced();

        System.out.println("\n--- Kotlin: Builder Inference ---");
        BuilderInferenceDemoKt.demonstrateBuilderInference();

        System.out.println("\n--- Kotlin: Type-Safe Builders ---");
        TypeSafeBuildersKt.demonstrateTypeSafeBuilders();

        System.out.println("\n--- Kotlin: Context Parameters ---");
        ContextParametersDemoKt.demonstrateContextParameters();

        System.out.println("\n--- Kotlin: Inline Functions ---");
        InlineFunctionsDemoKt.demonstrateInlineFunctions();

        System.out.println("\n--- Kotlin: Operator Overloading ---");
        OperatorOverloadingDemoKt.demonstrateOperatorOverloading();

        System.out.println("\n--- Kotlin: Unused Return Value Checker ---");
        CheckResultDemoKt.demonstrateUnusedReturnValueChecker();

        System.out.println("\n--- Kotlin: Advanced Classes ---");
        ClassesAdvancedKt.demonstrateClassesAdvanced();

        System.out.println("\n--- Kotlin: Data Classes ---");
        DataClassesDemoKt.demonstrateDataClasses();

        System.out.println("\n--- Kotlin: Advanced Extensions ---");
        ExtensionsAdvancedKt.demonstrateExtensionsAdvanced();

        System.out.println("\n--- Kotlin: Advanced Interfaces ---");
        InterfacesAdvancedKt.demonstrateInterfacesAdvanced();

        System.out.println("\n--- Kotlin: Class Delegation ---");
        DelegationDemoKt.demonstrateDelegation();

        System.out.println("\n--- Kotlin: Advanced Inheritance Rules ---");
        InheritanceRulesDemoKt.demonstrateInheritanceRules();

        System.out.println("\n--- Kotlin: Advanced Object Declarations ---");
        ObjectDeclarationsAdvancedKt.demonstrateObjectDeclarationsAdvanced();

        System.out.println("\n--- Kotlin: This Expressions ---");
        ThisExpressionsDemoKt.demonstrateThisExpressions();

        System.out.println("\n--- Kotlin: Sealed Classes ---");
        SealedClassesDemoKt.demonstrateSealedClasses();

        System.out.println("\n--- Kotlin: Enums & Value Classes ---");
        EnumAndInlineDemoKt.demonstrateEnumAndInlineClasses();

        System.out.println("\n--- Kotlin: Nested & Inner Classes ---");
        NestedClassesDemoKt.demonstrateNestedClasses();

        System.out.println("\n--- Kotlin: Advanced Functional & Property Frameworks ---");
        Lessons52To58DemoKt.demonstrateLessons52To58();

        System.out.println("\n--- Kotlin: Equality Mechanics ---");
        EqualityDemoKt.demonstrateEqualityOperations();

        System.out.println("\n--- Kotlin: Generics ---");
        GenericsDemoKt.demonstrateGenerics();

        System.out.println("\n--- Kotlin: Async Programming Overview ---");
        AsyncProgrammingOverviewKt.demonstrateAsyncOverview();

        System.out.println("\n--- Kotlin: Coroutines Overview ---");
        CoroutinesOverviewKt.demonstrateCoroutinesOverview();

        System.out.println("\n--- Kotlin: Reflection ---");
        ReflectionDemoKt.demonstrateReflection();

        System.out.println("\n--- Kotlin: Destructuring Declarations ---");
        DestructuringDemoKt.demonstrateDestructuring();

        System.out.println("\n--- Kotlin: Grammar & Syntax ---");
        GrammarSyntaxDemoKt.demonstrateGrammar();

        System.out.println("\n--- Kotlin: Booleans ---");
        BooleansKt.demonstrateBooleans();

        System.out.println("\n--- Kotlin: Characters ---");
        CharactersKt.demonstrateCharacters();

        System.out.println("\n--- Kotlin: Strings ---");
        StringsKt.demonstrateStrings();

        System.out.println("\n--- Kotlin: Arrays ---");
        ArraysKt.demonstrateArrays();

        // Calling objects from Java
        DoAuth.INSTANCE.takeParams("java_user", "j4v4_pass");
        BigBen.Bonger.getBongs(2);
        boolean isValid = TourUser.Companion.isValidEmail("test@java.com");
        System.out.println("Email valid from Java? " + isValid);
    }
}
